# Generated by Django 5.0.3 on 2024-04-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Password2',
        ),
    ]
