# Generated by Django 5.0.3 on 2024-04-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_remove_details_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('C1', models.CharField(max_length=20)),
                ('C2', models.CharField(max_length=20)),
                ('C3', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Language', models.CharField(max_length=50)),
                ('Aadhar', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Profilepic', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
