# Generated by Django 5.0.3 on 2024-04-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_detail_delete_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='C1',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='C2',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='C3',
        ),
    ]
