# Generated by Django 5.0.3 on 2024-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_details_delete_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Profilepic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
