# Generated by Django 5.0.3 on 2024-05-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_alter_bookdata_photo_alter_details_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Name',
            new_name='Fullname',
        ),
        migrations.AlterField(
            model_name='details',
            name='Aadhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='details',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='details',
            name='Language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='Username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
