# Generated by Django 5.0.3 on 2024-05-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_rename_name_details_fullname_alter_details_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
