# Generated by Django 5.0.3 on 2024-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_alter_bookdata_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Fullname',
            field=models.CharField(max_length=300),
        ),
    ]
