# Generated by Django 5.0.3 on 2024-05-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_alter_details_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
