# Generated by Django 5.0.3 on 2024-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_contact_alter_bookdata_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('issuedate', models.DateField()),
                ('returndate', models.DateField()),
            ],
        ),
    ]
