# Generated by Django 5.0.3 on 2024-06-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0013_issuedbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
